# Generated by Django 5.0.2 on 2024-02-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
