# Generated by Django 5.0.2 on 2024-02-15 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=100)),
                ('surname', models.CharField(default='1234', max_length=100)),
                ('mobile_number', models.CharField(default='XXXXXXXXXX', max_length=15)),
                ('address', models.CharField(default='No Address Provided', max_length=255)),
                ('postcode', models.CharField(default='XXXXXX', max_length=20)),
                ('area', models.CharField(default='Unknown Area', max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('education', models.CharField(default='No Education Information', max_length=255)),
                ('country', models.CharField(default='Unknown Country', max_length=100)),
                ('state_region', models.CharField(default='Unknown Region', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('captcha_score', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
