# Generated by Django 5.0.2 on 2024-03-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='state_region',
            field=models.CharField(default='Unknown State', max_length=100),
        ),
    ]
