# Generated by Django 5.0.2 on 2024-03-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_userprofile_state_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile_image.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state_region',
            field=models.CharField(default='Unknown Region', max_length=100),
        ),
    ]
