# Generated by Django 5.0.2 on 2024-02-27 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanitizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aims Hospital', max_length=100)),
                ('street', models.CharField(default='Street 99', max_length=255)),
                ('city', models.CharField(default='City 99', max_length=100)),
                ('state', models.CharField(default='State 99', max_length=100)),
                ('zip', models.CharField(default='XXXXXX', max_length=20)),
                ('contactperson', models.CharField(default='Virju', max_length=100)),
                ('phone', models.CharField(default='XXXXXXXXXX', max_length=10)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='sanitizerDoc/')),
                ('isChecked', models.BooleanField(default=True)),
                ('isSubmitted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanitizer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cases', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trending_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plofile.trendingdata')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=100)),
                ('surname', models.CharField(default='1234', max_length=100)),
                ('mobile_number', models.CharField(default='XXXXXXXXXX', max_length=15)),
                ('address', models.CharField(default='No Address Provided', max_length=255)),
                ('postcode', models.CharField(default='XXXXXX', max_length=20)),
                ('area', models.CharField(default='Unknown Area', max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('education', models.CharField(default='No Education Information', max_length=255)),
                ('country', models.CharField(default='Unknown Country', max_length=100)),
                ('state_region', models.CharField(default='Unknown Region', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
