# Generated by Django 5.0.2 on 2024-02-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
