# Generated by Django 5.0.2 on 2024-02-26 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanitizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aims Hospital', max_length=100)),
                ('street', models.CharField(default='Street 99', max_length=255)),
                ('city', models.CharField(default='City 99', max_length=100)),
                ('state', models.CharField(default='State 99', max_length=100)),
                ('zip', models.CharField(default='XXXXXX', max_length=20)),
                ('contactperson', models.CharField(default='Virju', max_length=100)),
                ('phone', models.CharField(default='XXXXXXXXXX', max_length=10)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='sanitizerDoc/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sanitizer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
