# Generated by Django 5.0.2 on 2024-02-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0002_alter_disease_created_at_alter_disease_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitizer',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='Sanitizerprofile/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sanitizer',
            name='certificate',
            field=models.ImageField(default=1, upload_to='sanitizerDoc/'),
            preserve_default=False,
        ),
    ]
