# Generated by Django 5.0.2 on 2024-02-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0002_sanitizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitizer',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
