# Generated by Django 5.0.2 on 2024-02-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0003_sanitizer_ischecked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitizer',
            name='isChecked',
            field=models.BooleanField(default=True),
        ),
    ]
