# Generated by Django 5.0.2 on 2024-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0003_sanitizer_profile_image_alter_sanitizer_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitizer',
            name='CPemail',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sanitizer',
            name='CPphone',
            field=models.CharField(default='XXXXXXXXXX', max_length=10),
        ),
    ]
