# Generated by Django 5.0.2 on 2024-02-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0004_alter_sanitizer_ischecked'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitizer',
            name='isSubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sanitizer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
