# Generated by Django 5.0.2 on 2024-02-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0004_sanitizer_cpemail_sanitizer_cpphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanitizer',
            name='latitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanitizer',
            name='longitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
