# Generated by Django 5.0.2 on 2024-02-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0005_sanitizer_issubmitted_sanitizer_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitizer',
            name='certificate',
            field=models.ImageField(default=1, upload_to='sanitizerDoc/'),
            preserve_default=False,
        ),
    ]
