# Generated by Django 5.0.2 on 2024-02-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0005_sanitizer_latitude_sanitizer_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitizer',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sanitizer',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
    ]
