# Generated by Django 5.0.2 on 2024-02-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0006_alter_sanitizer_latitude_alter_sanitizer_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
