# Generated by Django 5.0.2 on 2024-02-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0006_alter_sanitizer_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitizer',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='sanitizerDoc/'),
        ),
    ]
