# Generated by Django 5.0.2 on 2024-02-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0007_alter_disease_created_at_alter_disease_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='updated_at',
        ),
    ]
