# Generated by Django 5.0.2 on 2024-02-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0008_remove_disease_created_at_remove_disease_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
