# Generated by Django 5.0.2 on 2024-02-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0009_disease_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='created_at',
        ),
    ]
