# Generated by Django 5.0.2 on 2024-02-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0009_alter_trendingdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingdata',
            old_name='disease_name',
            new_name='name',
        ),
    ]
