# Generated by Django 5.0.2 on 2024-02-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0010_remove_disease_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingdata',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
