# Generated by Django 5.0.2 on 2024-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0011_alter_trendingdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingdata',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
