# Generated by Django 5.0.2 on 2024-02-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0012_alter_trendingdata_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingdata',
            old_name='name',
            new_name='disease_name',
        ),
    ]
