# Generated by Django 5.0.2 on 2024-03-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0013_alter_trendingdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitizer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sanitizer',
            name='state',
            field=models.CharField(choices=[], default='Andaman and Nicobar Islands', max_length=100),
        ),
    ]
