# Generated by Django 5.0.2 on 2024-03-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0016_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile_image.jpg', null=True, upload_to='profile/'),
        ),
    ]
