# Generated by Django 5.0.2 on 2024-03-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0017_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
