# Generated by Django 5.0.2 on 2024-03-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0018_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitizer',
            name='city',
            field=models.CharField(choices=[('Bhubaneswar', 'Bhubaneswar'), ('Maihar', 'Maihar'), ('Cuttack', 'Cuttack'), ('Rourkela', 'Rourkela'), ('Puri', 'Puri'), ('Sambalpur', 'Sambalpur'), ('Brahmapur', 'Brahmapur'), ('Balasore', 'Balasore'), ('Jharsuguda', 'Jharsuguda'), ('Baripada', 'Baripada'), ('Bargarh', 'Bargarh')], default='City 99', max_length=100),
        ),
        migrations.AlterField(
            model_name='trendingdata',
            name='city',
            field=models.CharField(choices=[('Bhubaneswar', 'Bhubaneswar'), ('Maihar', 'Maihar'), ('Cuttack', 'Cuttack'), ('Rourkela', 'Rourkela'), ('Puri', 'Puri'), ('Sambalpur', 'Sambalpur'), ('Brahmapur', 'Brahmapur'), ('Balasore', 'Balasore'), ('Jharsuguda', 'Jharsuguda'), ('Baripada', 'Baripada'), ('Bargarh', 'Bargarh')], max_length=100),
        ),
    ]
