# Generated by Django 5.0.2 on 2024-03-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0019_alter_sanitizer_city_alter_trendingdata_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitizer',
            name='certificate',
            field=models.ImageField(blank=True, upload_to='sanitizerDoc/'),
        ),
        migrations.AlterField(
            model_name='sanitizer',
            name='latitude',
            field=models.CharField(default='XX.XXXXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='sanitizer',
            name='longitude',
            field=models.CharField(default='XX.XXXXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='sanitizer',
            name='profile_image',
            field=models.ImageField(blank=True, default='Sanitizerprofile/default_profile_image.jpg', null=True, upload_to='Sanitizerprofile/'),
        ),
    ]
