# Generated by Django 5.0.2 on 2024-04-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0020_alter_sanitizer_certificate_alter_sanitizer_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitizer',
            name='name',
            field=models.CharField(default='Aiims Hospital', max_length=100),
        ),
    ]
