# Generated by Django 5.0.2 on 2024-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plofile', '0021_alter_sanitizer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitizer',
            name='city',
            field=models.CharField(choices=[('Balaghat', 'Balaghat'), ('Barwani', 'Barwani'), ('Betul', 'Betul'), ('Bharhut', 'Bharhut'), ('Bhind', 'Bhind'), ('Bhojpur', 'Bhojpur'), ('Bhopal', 'Bhopal'), ('Burhanpur', 'Burhanpur'), ('Chhatarpur', 'Chhatarpur'), ('Chhindwara', 'Chhindwara'), ('Damoh', 'Damoh'), ('Datia', 'Datia'), ('Dewas', 'Dewas'), ('Dhar', 'Dhar'), ('Dr. Ambedkar Nagar (Mhow)', 'Dr. Ambedkar Nagar (Mhow)'), ('Guna', 'Guna'), ('Gwalior', 'Gwalior'), ('Hoshangabad', 'Hoshangabad'), ('Indore', 'Indore'), ('Itarsi', 'Itarsi'), ('Jabalpur', 'Jabalpur'), ('Jhabua', 'Jhabua'), ('Khajuraho', 'Khajuraho'), ('Khandwa', 'Khandwa'), ('Khargone', 'Khargone'), ('Maheshwar', 'Maheshwar'), ('Mandla', 'Mandla'), ('Mandsaur', 'Mandsaur'), ('Morena', 'Morena'), ('Murwara', 'Murwara'), ('Narsimhapur', 'Narsimhapur'), ('Narsinghgarh', 'Narsinghgarh'), ('Narwar', 'Narwar'), ('Neemuch', 'Neemuch'), ('Nowgong', 'Nowgong'), ('Orchha', 'Orchha'), ('Panna', 'Panna'), ('Raisen', 'Raisen'), ('Rajgarh', 'Rajgarh'), ('Ratlam', 'Ratlam'), ('Rewa', 'Rewa'), ('Sagar', 'Sagar'), ('Sarangpur', 'Sarangpur'), ('Satna', 'Satna'), ('Sehore', 'Sehore'), ('Seoni', 'Seoni'), ('Shahdol', 'Shahdol'), ('Shajapur', 'Shajapur'), ('Sheopur', 'Sheopur'), ('Shivpuri', 'Shivpuri'), ('Ujjain', 'Ujjain'), ('Vidisha', 'Vidisha'), ('Maihar', 'Maihar')], default='City 99', max_length=100),
        ),
        migrations.AlterField(
            model_name='sanitizer',
            name='state',
            field=models.CharField(choices=[('Madhya Pradesh', 'Madhya Pradesh')], default='State 99', max_length=100),
        ),
        migrations.AlterField(
            model_name='trendingdata',
            name='city',
            field=models.CharField(choices=[('Balaghat', 'Balaghat'), ('Barwani', 'Barwani'), ('Betul', 'Betul'), ('Bharhut', 'Bharhut'), ('Bhind', 'Bhind'), ('Bhojpur', 'Bhojpur'), ('Bhopal', 'Bhopal'), ('Burhanpur', 'Burhanpur'), ('Chhatarpur', 'Chhatarpur'), ('Chhindwara', 'Chhindwara'), ('Damoh', 'Damoh'), ('Datia', 'Datia'), ('Dewas', 'Dewas'), ('Dhar', 'Dhar'), ('Dr. Ambedkar Nagar (Mhow)', 'Dr. Ambedkar Nagar (Mhow)'), ('Guna', 'Guna'), ('Gwalior', 'Gwalior'), ('Hoshangabad', 'Hoshangabad'), ('Indore', 'Indore'), ('Itarsi', 'Itarsi'), ('Jabalpur', 'Jabalpur'), ('Jhabua', 'Jhabua'), ('Khajuraho', 'Khajuraho'), ('Khandwa', 'Khandwa'), ('Khargone', 'Khargone'), ('Maheshwar', 'Maheshwar'), ('Mandla', 'Mandla'), ('Mandsaur', 'Mandsaur'), ('Morena', 'Morena'), ('Murwara', 'Murwara'), ('Narsimhapur', 'Narsimhapur'), ('Narsinghgarh', 'Narsinghgarh'), ('Narwar', 'Narwar'), ('Neemuch', 'Neemuch'), ('Nowgong', 'Nowgong'), ('Orchha', 'Orchha'), ('Panna', 'Panna'), ('Raisen', 'Raisen'), ('Rajgarh', 'Rajgarh'), ('Ratlam', 'Ratlam'), ('Rewa', 'Rewa'), ('Sagar', 'Sagar'), ('Sarangpur', 'Sarangpur'), ('Satna', 'Satna'), ('Sehore', 'Sehore'), ('Seoni', 'Seoni'), ('Shahdol', 'Shahdol'), ('Shajapur', 'Shajapur'), ('Sheopur', 'Sheopur'), ('Shivpuri', 'Shivpuri'), ('Ujjain', 'Ujjain'), ('Vidisha', 'Vidisha'), ('Maihar', 'Maihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trendingdata',
            name='state',
            field=models.CharField(choices=[('Madhya Pradesh', 'Madhya Pradesh')], max_length=100),
        ),
    ]
