# Generated by Django 5.0.2 on 2024-04-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='adv_name',
            field=models.CharField(max_length=50),
        ),
    ]
