# Generated by Django 5.0.2 on 2024-04-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_alter_advertisement_adv_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partnership/')),
            ],
        ),
        migrations.CreateModel(
            name='sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sponsor/')),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='adv_name',
        ),
    ]
