# Generated by Django 5.0.2 on 2024-04-16 14:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_notification_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='spherepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
    ]
