# Generated by Django 5.0.2 on 2024-04-29 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_spherecomment_spherepost_comments_delete_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spherepost',
            name='comments',
        ),
        migrations.AddField(
            model_name='spherepost',
            name='comments',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='sphere_post_comments', to='home.spherecomment'),
            preserve_default=False,
        ),
    ]
