# Generated by Django 5.0.2 on 2024-04-29 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_spherepost_comments_spherepost_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spherepost',
            name='comments',
        ),
        migrations.AlterField(
            model_name='spherecomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.spherepost'),
        ),
    ]
