# Generated by Django 5.0.2 on 2024-05-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
