# Generated by Django 5.0.2 on 2024-02-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0002_post_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='cont',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_image',
        ),
    ]
