# Generated by Django 5.0.2 on 2024-05-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0002_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='../../static/assets/images/blogs/sample.jpeg', upload_to='blog_images'),
        ),
    ]
