# Generated by Django 5.0.2 on 2024-02-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0003_rename_content_post_cont_remove_post_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cont',
            new_name='content',
        ),
    ]
