# Generated by Django 5.0.2 on 2024-02-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0004_rename_cont_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
